import json
import time
from openai import OpenAI


purchase_orders = {
    "PO-4821": {
        "vendor": "ABC Logistics",
        "amount": 12000,
        "currency": "USD",
    }
}


def lookup_purchase_order(po_number):
    return purchase_orders.get(
        po_number,
        {"error": f"{po_number} not found"},
    )


client = OpenAI(
    base_url="http://127.0.0.1:8080/v1",
    api_key="not-needed",
)


tools = [
    {
        "type": "function",
        "function": {
            "name": "lookup_purchase_order",
            "description": "Look up a purchase order by PO number.",
            "parameters": {
                "type": "object",
                "properties": {
                    "po_number": {
                        "type": "string",
                        "description": "Purchase order number, for example PO-4821",
                    }
                },
                "required": ["po_number"],
            },
        },
    }
]


messages = [
    {
        "role": "system",
        "content": (
            "You are an accounts payable assistant. "
            "Use the available tool whenever purchase order data must be checked. "
            "After receiving the tool result, give a concise factual answer. "
            "State the purchase order amount, invoice amount, and discrepancy. "
            "Do not speculate beyond the available data. "
            "Do not ask follow-up questions."
        ),
    },
    {
        "role": "user",
        "content": (
            "I received an invoice from ABC Logistics for $12,450. "
            "It references purchase order PO-4821. "
            "Please check the purchase order and identify any discrepancy."
        ),
    },
]


workflow_start = time.perf_counter()

# First model call: choose tool and generate arguments
start = time.perf_counter()

response = client.chat.completions.create(
    model="lfm2.5-2.6b",
    messages=messages,
    tools=tools,
    tool_choice="auto",
    max_tokens=400,
)

first_call_latency = time.perf_counter() - start

print(
    f"\nFirst model call "
    f"(tool selection + argument generation): "
    f"{first_call_latency:.2f} seconds"
)

assistant_message = response.choices[0].message

print("\nRaw model response:")
print(assistant_message)

if not assistant_message.tool_calls:
    print("\nModel did not call a tool.")
    raise SystemExit


tool_call = assistant_message.tool_calls[0]

print("\nTool selected:")
print(tool_call.function.name)

print("\nArguments generated by model:")
print(tool_call.function.arguments)


arguments = json.loads(tool_call.function.arguments)

tool_result = lookup_purchase_order(
    po_number=arguments["po_number"]
)

print("\nActual Python function result:")
print(tool_result)


messages.append(assistant_message)
messages.append(
    {
        "role": "tool",
        "tool_call_id": tool_call.id,
        "content": json.dumps(tool_result),
    }
)


# Second model call: interpret tool result and produce final answer
start = time.perf_counter()

final_response = client.chat.completions.create(
    model="lfm2.5-2.6b",
    messages=messages,
    tools=tools,
    max_tokens=800,
)

second_call_latency = time.perf_counter() - start

print(
    f"\nSecond model call "
    f"(tool-result interpretation + final generation): "
    f"{second_call_latency:.2f} seconds"
)

print("\nFinal answer:")
print(final_response.choices[0].message.content)

print("\nFinish reason:")
print(final_response.choices[0].finish_reason)

print("\nUsage:")
print(final_response.usage)

workflow_elapsed = time.perf_counter() - workflow_start

non_model_overhead = (
    workflow_elapsed
    - first_call_latency
    - second_call_latency
)

print(
    f"\nTotal end-to-end workflow latency: "
    f"{workflow_elapsed:.2f} seconds"
)

print(
    f"Approximate non-model orchestration overhead: "
    f"{non_model_overhead:.2f} seconds"
)
